import 'package:hokoo_flutter/view/Utils/Settings/app_images.dart';

class UserLivestreamingComment {
  String message;
  String user;
  String image;

  UserLivestreamingComment({required this.message, required this.user, required this.image});
}

List<UserLivestreamingComment> userLiveStreamingCommentList = [
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
  UserLivestreamingComment(message: "How are You?", user: "Lily", image: AppImages.storyModel12),
  UserLivestreamingComment(message: "Hello Dear", user: "Milly", image: AppImages.storyModel22),
  UserLivestreamingComment(message: "9876543210 it is my mobile number", user: "Senorita", image: AppImages.storyModel41),
  UserLivestreamingComment(message: "Your Hotness is beating me everytime?", user: "Rio", image: AppImages.storyModel61),
  UserLivestreamingComment(message: "i drop my cap for you?", user: "Angle", image: AppImages.storyModel52),
  UserLivestreamingComment(message: "classy shot and awesome background too", user: "Brownie", image: AppImages.storyModel1),
  UserLivestreamingComment(message: "give me your mobile number", user: "Zara", image: AppImages.storyModel2),
  UserLivestreamingComment(message: "can we talk?", user: "Rio", image: AppImages.storyModel3),
  UserLivestreamingComment(message: "looking very very hot", user: "Angle", image: AppImages.storyModel4),
  UserLivestreamingComment(message: "let's hangout", user: "Lily", image: AppImages.storyModel5),
];
